default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgres
  username: postgres
  password: valesca
  port: 5432

test:
  <<: *default
  database: twitterclone_test
  username: postgres
  password: valesca
  port: 5432

production:
  <<: *default
  # database: twitterclone_production
  # sername: twitterclone
  # password: <%= ENV["TWITTERCLONE_DATABASE_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>
